### ISSUE TITLE
Multi language ?

### ISSUE THREAD

**Issue by KatyPurry** [fawadasaurus/d4-aspect-tracker#16]
Hello,
Thank you for your awesome tool ! It’s a game changer ! I’m playing in French and it’s not easy to find / retrieve an item. Do you plan to add more language ? I don’t know if it’s easy to implement (I hope there are an API).

**Comment by fawadasaurus** [comment]
Ok.  I will work on this soon.

**Comment by KatyPurry** [comment]
Awesome ! Thank you

**Comment by fawadasaurus** [comment]
Ok. This is ready. You will see a drop-down. You may need to do a refresh of the page to get all the language translated data.
