### ISSUE TITLE
Missing Aspect Type: Weapon

### ISSUE THREAD

**Issue by Barrowulf** [fawadasaurus/d4-aspect-tracker#17]
I think the aspect type, Weapon, is missing.

For example, if you view the barbarian aspect, Battle-Mad, its type will be displayed as "null".

Thank you!

**Comment by fawadasaurus** [comment]
Hi.  Does this aspect exist in the game? (did you find it?)

I am trying to determine if I need to just not show this at all or if the underlying database that I am using is flawed.

As far as I know, there is no aspect type of "Weapon" but there is an aspect type of "Offensive".

**Comment by Barrowulf** [comment]
Hi, it certainly does exist in the game, I have a couple of them extracted too.

I went on Maxroll.gg and under Resources > Wiki > Legendary Aspects you can see a list of all aspects.  Battle-Mad is the only one listed as solely a Weapon aspect.  Which is odd, since I thought there would be more, but I mostly play barbarian.

Its extracted name is Battle-Mad Weapon Aspect and its icon is unique as well - two crossed swords.

Hope this helps, thank you!

**Comment by fawadasaurus** [comment]
Thanks for confirming.  I have made the requested adjustment!

Please spread the word of the tool on any forums and chat channels you may browse so our community can grow and our tool be made better.
