### ISSUE TITLE
Serpentine Aspect for Sorcerer not showing 

### ISSUE THREAD

**Issue by KatKelsch38** [fawadasaurus/d4-aspect-tracker#18]

**Comment by fawadasaurus** [comment]
<img width="718" alt="image" src="https://github.com/fawadasaurus/d4-aspect-tracker/assets/99134191/d0c6c85c-cbc6-4988-9238-355dd2bc78ec">

What language? In english it seems to show up fine.

Do you have an item slot filter set?  It is offensive aspect so if you have the item slot of "chest" or "boots" then it will not show.
