### ISSUE TITLE
Reverse calculation for cooldown related aspects when calculating for 2h weapons and amulets.

### ISSUE THREAD

**Issue by rafigalb** [fawadasaurus/d4-aspect-tracker#19]
With Aspects like Eluding and Seismic-shift, for example, lower number is better.

![image](https://github.com/fawadasaurus/d4-aspect-tracker/assets/46434351/a3fc9bf4-4835-41b0-8a9d-cac87322589c)

**Comment by fawadasaurus** [comment]
Can you please tell me the value on 2hander and what is the actual expected value?

**Comment by rafigalb** [comment]
The in-game description on the 2h Seismic-shift reads:
`Earth Spike launches spikes in a line and has a 0.5 [1.0 - 0.5] second cooldown.`

I actually entered it wrong on the first screenshot, here is how it shows currently in the tool:

![image](https://github.com/fawadasaurus/d4-aspect-tracker/assets/46434351/6c403ced-10e5-4435-ba6b-665a29eed00b)

**Comment by fawadasaurus** [comment]
Thanks. I'll need to find all the "inverse" aspects.

**Comment by fawadasaurus** [comment]
```

  let inverseAspects = [
    'Seismic-shift',
    'Blood-bathed',
    'Eluding',
    'Frostblitz',
    'Gravitational',
    "Infiltrator's",
    'of Piercing Cold',
    'Serpentine',
    'Tidal',
  ]
  ```
