### ISSUE TITLE
Input limited to numbers

### ISSUE THREAD

**Issue by Senne-DC** [fawadasaurus/d4-aspect-tracker#25]
Hey good stuff helps me a lot tracking my aspects!
I like to include the level requirement of the aspect as well as the location/character name where I have it stored. I did this by just following a format: 
{aspectValue}/{levelReq}/{location}
![image](https://github.com/fawadasaurus/d4-aspect-tracker/assets/2308797/b83bd779-d77a-4a69-9910-ee35d2745248)
However I am now no longer able to input something like that since the input is limited to numbers. 
I've resorted to now using the decimal separator to indicate the level but haven't found a way to also indicate the location. :)
![image](https://github.com/fawadasaurus/d4-aspect-tracker/assets/2308797/d9fb389b-8cb5-4688-a120-23b2ed064556)

Just my opinion of course but could we remove the number restriction? Perhaps there is still some way to keep the number keyboard for mobile but not limit the input?

Thanks!

**Comment by fawadasaurus** [comment]
Does the level requirement have an impact on anything? I thought you could put any level aspect on any item?

**Comment by Senne-DC** [comment]
I mostly want to know about it when leveling an alt. When you put a level 90 aspect on a level 50 item it becomes a level 90 item. So I can't use a lvl 90 aspect for my lvl 60 character as it won't be able to use the item.

**Comment by fawadasaurus** [comment]
ok.  Thanks. I'm not sure why blizz makes leveling alts so hard
I have a fun idea to solve your problem.  I'll implement it and let you know when its ready.

**Comment by fawadasaurus** [comment]
Hello.  a new (optional) note field has been added.  I tried to do "tags" but it was a lot more complicated than needed.
