### ISSUE TITLE
"Raw Might", "of Elements", etc. aspects are in data set but doesn't appear on web site

### ISSUE THREAD

**Issue by bbugh** [fawadasaurus/d4-aspect-tracker#32]
👋 Hi, thanks for this cool thing. I can't keep track of all of this stuff and it's been helpful. 

There's no "raw might" aspect appearing on the page though.

It appears in lothrik's data: https://github.com/Lothrik/diablo4-build-calc/blob/1e9c25471cb9a916f5ff2cac4caf822ef5ece6c5/parser/codex-values.js#L715

And it's in /app/public/aspects.json https://github.com/fawadasaurus/d4-aspect-tracker/blob/154624d5afc04c466db9ed04021a4a8aacf8cd9a/app/public/aspects.json#L2962

But it's not in /app/aspects.json https://github.com/fawadasaurus/d4-aspect-tracker/blob/154624d5afc04c466db9ed04021a4a8aacf8cd9a/app/aspects.json

which is read by https://github.com/fawadasaurus/d4-aspect-tracker/blob/154624d5afc04c466db9ed04021a4a8aacf8cd9a/app/src/App.svelte#L98

so no "raw might"

**Comment by bbugh** [comment]
Same thing with "of elements" https://github.com/fawadasaurus/d4-aspect-tracker/blob/154624d5afc04c466db9ed04021a4a8aacf8cd9a/app/public/aspects.json#L3961

does not appear in /app/aspects.json https://github.com/fawadasaurus/d4-aspect-tracker/blob/154624d5afc04c466db9ed04021a4a8aacf8cd9a/app/aspects.json

**Comment by bbugh** [comment]
Also missing "of slaughter"

https://github.com/fawadasaurus/d4-aspect-tracker/blob/154624d5afc04c466db9ed04021a4a8aacf8cd9a/app/public/aspects.json#L3998

**Comment by fawadasaurus** [comment]
Ok.  Strange.  Let me look. I just did a re-sync on the lothrik data a few days ago. Let me remember how this works again :)

**Comment by fawadasaurus** [comment]
Ok.  The file didn't seem to get updated properly last time. It has been updated now and is working now.

Thanks for reporting the issue!
