### ISSUE TITLE
Two independent values

### ISSUE THREAD

**Issue by denisborovikov** [fawadasaurus/d4-aspect-tracker#9]
As you mentioned [here](https://github.com/fawadasaurus/d4-aspect-tracker/issues/5#issuecomment-1614116690), some aspects require recording two values. Can you give me an example? 

All aspects I've seen before, even if they have two parameters, are all connected by a simple ratio of 1 to 2, 1 to 3, etc. 

I.e.

```
You gain x[0.25-0.5]% increased Armor for 4.0 seconds when you deal any form of damage, stacking up to x[25-50]%.
```
there's always a ratio of 1 to 100, you gain 0.25% up to 25%, or you gain 0.45 up to 45%. 

My point here is there's no need to record two numbers for such items.

Update: 

Actually, this kind of aspects might require two numbers
```
Leap creates an Earthquake that deals [#] Physical damage over 4 seconds. While standing in Earthquakes, you gain [5-15]% increased Damage Reduction.
```
but I've never seen this in the game.

**Comment by UweKnopf** [comment]
I believe the # values represent dynamic ranges based on your level. 

I found this [reddit post](https://www.reddit.com/r/diablo4/comments/145pcz7/please_help_with_understanding_these_aspect_ranges/) that seemingly confirms another example of that (although I too haven't seen any of these yet). Unrelated: looking at the post a bit more and comparing it with our aspect of the Crowded Sage, what strikes me as very weird is that the second value doesn't even have a range and is pinned in the JSON to 50. 

Might be worth investigating the accuracy of the db a bit.

As far as I can count, only 5 aspects have 2 values, where one is based on levelling. They might still be linked like in your first example, although that is just a guess. 

I honestly like the idea of doing these ratios and then just asking the user to type in the first value and auto create the second one. If the dynamic ranges are connected, we could just ask the user for the value he got for the dynamic value and from there calculate the non level depend value. That would however entail a lot of hardcoding and blow up our json, and I am really not sure if all of that added complexity is worth it for just 5 aspects.

**Comment by denisborovikov** [comment]
This is not exactly what I meant. The idea of the tracker is to keep track of the better aspects. If the aspect has two values connected by the ratio, recording both of them doesn't make much sense. It's enough to save just one of them and compare if it's better than the previously recorded one. The only thing the user has to do is always to record only the 1st or only the 2nd parameter from the aspect's description and don't mix them to avoid confusion.

I like having only one numeric input, as in my previous implementation. I'd add a radio button or some kind of selector to select the type of item instead of using input for this purpose.

**Comment by fawadasaurus** [comment]
Yea after further review I think that the initial implementation is sufficient.

Need to investigate the ratio for all the aspects to automatically calculate it. 

I propose to add a drop-down next to it to specify the item slot /type. (optional). To me that is important so I can quickly find the aspect again.

**Comment by Senne-DC** [comment]
FYI I have found one where it has 2 separate values and you are not able to determine the 2nd value based on the 1st.
![image](https://github.com/fawadasaurus/d4-aspect-tracker/assets/2308797/41b3221e-eff1-4afd-bf64-9a435602c0d4)
![image](https://github.com/fawadasaurus/d4-aspect-tracker/assets/2308797/e6de540b-6fc3-4edc-a285-dbc12852eb4e)

**Comment by fawadasaurus** [comment]
thanks.  That was an annoying one as it has both a double entry and only the second value is inverse (lower is better).

Its fixed

**Comment by denisborovikov** [comment]
There are some other aspects I've sen where a lower value is better, the range goes from lower to higher. This is actually very useful if the range is inverted.

**Comment by fawadasaurus** [comment]
Yes. I have already handled all the ones that I saw. I may have missed some so report it (or update it) if you find some.
